name: "build pipeline for web release"

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter --version

  build-web:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: flutter build web
      - name: Copy build settings to build folder
        run: cp netlify.toml build/web/

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUBACCESS_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './build/web'
          comment-on-commit: false


#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter build web
#
#      # copy file for netlify.toml
#      - name: Copy build settings to build folder
#        run: cp netlify.toml build/web/
#
#      # deploy application to netlify
#      - name: Deploy production to Netlify
#        uses: South-Paw/action-netlify-deploy@v1.2.0
#        with:
#          github-token: ${{ secrets.GITHUBACCESS_TOKEN }}
#          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
#          build-dir: './build/web'
#          comment-on-commit: false